"""add unique True to cloumns

Revision ID: 8904497fdc61
Revises: ef895a043b79
Create Date: 2024-08-12 14:45:54.616723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8904497fdc61'
down_revision: Union[str, None] = 'ef895a043b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_city_name', table_name='city')
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=True)
    op.add_column('coach', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index('ix_coach_account', table_name='coach')
    op.create_index(op.f('ix_coach_account'), 'coach', ['account'], unique=True)
    op.create_unique_constraint(None, 'coach', ['phone'])
    op.create_unique_constraint(None, 'coach', ['email'])
    op.drop_index('ix_coursecategory_name', table_name='coursecategory')
    op.create_index(op.f('ix_coursecategory_name'), 'coursecategory', ['name'], unique=True)
    op.create_unique_constraint(None, 'gym', ['name'])
    op.create_unique_constraint(None, 'gym', ['address'])
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_constraint(None, 'gym', type_='unique')
    op.drop_constraint(None, 'gym', type_='unique')
    op.drop_index(op.f('ix_coursecategory_name'), table_name='coursecategory')
    op.create_index('ix_coursecategory_name', 'coursecategory', ['name'], unique=False)
    op.drop_constraint(None, 'coach', type_='unique')
    op.drop_constraint(None, 'coach', type_='unique')
    op.drop_index(op.f('ix_coach_account'), table_name='coach')
    op.create_index('ix_coach_account', 'coach', ['account'], unique=False)
    op.drop_column('coach', 'email')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.create_index('ix_city_name', 'city', ['name'], unique=False)
    # ### end Alembic commands ###
