"""fix Coach and gym link error

Revision ID: b7d4acf35f1c
Revises: 61aedb972658
Create Date: 2024-08-18 00:27:59.907688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b7d4acf35f1c'
down_revision: Union[str, None] = '61aedb972658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='coach')
    op.create_index(op.f('ix_coach_email'), 'coach', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_email'), table_name='coach')
    op.create_index('email', 'coach', ['email'], unique=True)
    # ### end Alembic commands ###
